# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ffcf879907e1dc1a2740f11f4edf26ba2e4b573895e1eba48adf11abf540ef2b42bc194c33e4e6e7ec6d0f65e6e0a52a59bbf6ca69288355dd400f6ae7f4368

test:
  secret_key_base: cc568e4b451a467bb886f2ac59451ccf4912d6f6dbd7f89cf82116278583697a9bdb995d638f1844a32456262cfe22e51bd9e7e75ff0cd18c9b1a9cc3c8d5445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
